package com.nurul.entity;
// Generated Apr 12, 2018 3:41:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Lecturer generated by hbm2java
 */
@Entity
@Table(name = "lecturer", catalog = "ujitarobby_attendance_system"
)
public class Lecturer implements java.io.Serializable {

    private String nik;
    private Department department;
    private Rolelecturer rolelecturer;
    private String name;
    private String password;
    private Set<ClassSchedule> classSchedules = new HashSet<ClassSchedule>(0);

    public Lecturer() {
    }

    public Lecturer(String nik, Department department, Rolelecturer rolelecturer,
            String name, String password) {
        this.nik = nik;
        this.department = department;
        this.rolelecturer = rolelecturer;
        this.name = name;
        this.password = password;
    }

    public Lecturer(String nik, Department department, Rolelecturer rolelecturer,
            String name, String password, Set<ClassSchedule> classSchedules) {
        this.nik = nik;
        this.department = department;
        this.rolelecturer = rolelecturer;
        this.name = name;
        this.password = password;
        this.classSchedules = classSchedules;
    }

    @Id

    @Column(name = "nik", unique = true, nullable = false, length = 8)
    public String getNik() {
        return this.nik;
    }

    public void setNik(String nik) {
        this.nik = nik;
    }

    @XmlTransient
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id", nullable = false)
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @XmlTransient
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "roleLecturer_id", nullable = false)
    public Rolelecturer getRolelecturer() {
        return this.rolelecturer;
    }

    public void setRolelecturer(Rolelecturer rolelecturer) {
        this.rolelecturer = rolelecturer;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lecturer")
    public Set<ClassSchedule> getClassSchedules() {
        return this.classSchedules;
    }

    public void setClassSchedules(Set<ClassSchedule> classSchedules) {
        this.classSchedules = classSchedules;
    }

}
