package com.nurul.entity;
// Generated Apr 12, 2018 3:41:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rolelecturer generated by hbm2java
 */
@Entity
@Table(name="rolelecturer"
    ,catalog="ujitarobby_attendance_system"
)
public class Rolelecturer  implements java.io.Serializable {


     private int id;
     private String status;
     private Set<Lecturer> lecturers = new HashSet<Lecturer>(0);

    public Rolelecturer() {
    }

	
    public Rolelecturer(int id, String status) {
        this.id = id;
        this.status = status;
    }
    public Rolelecturer(int id, String status, Set<Lecturer> lecturers) {
       this.id = id;
       this.status = status;
       this.lecturers = lecturers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rolelecturer")
    public Set<Lecturer> getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Set<Lecturer> lecturers) {
        this.lecturers = lecturers;
    }




}


